### ISSUE TITLE
id_token issued in the future

### ISSUE THREAD

**Issue by vsaraf** [18F/identity-oidc-expressjs#16]
After authentication, when the URL comes back to localhost, I see the following error in the browser:

id_token issued in the future
AssertionError [ERR_ASSERTION]: id_token issued in the future
    at Client.validateIdToken (D:\Work\login\node_modules\openid-client\lib\client.js:469:7)
    at grant.then.then.tokenset (D:\Work\login\node_modules\openid-client\lib\client.js:333:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

I am using the Sandbox Environment to test this. Please help me as to what can be done to fix this.

**Comment by vsaraf** [comment]
Never mind. "this.CLOCK_TOLERANCE" in "node_modules/openid-client/lib/client.js" was set to 0 and I set it to 5 (Give some skew time) and it worked like a charm.
